### ISSUE TITLE
database.rb:41 `join`:no implicit veronversion

### ISSUE THREAD

**Issue by kholbekj** [rubysec/bundler-audit#159]
On my CI server I get this (not the awesomest ruby version, but supported I suppose?)
```
/var/lib/gems/2.1.0/gems/bundler-audit-0.5.0/lib/bundler/audit/database.rb:41:in `join': no implicit conversion of nil into String (TypeError)
	from /var/lib/gems/2.1.0/gems/bundler-audit-0.5.0/lib/bundler/audit/database.rb:41:in `<class:Database>'
	from /var/lib/gems/2.1.0/gems/bundler-audit-0.5.0/lib/bundler/audit/database.rb:29:in `<module:Audit>'
	from /var/lib/gems/2.1.0/gems/bundler-audit-0.5.0/lib/bundler/audit/database.rb:24:in `<module:Bundler>'
	from /var/lib/gems/2.1.0/gems/bundler-audit-0.5.0/lib/bundler/audit/database.rb:23:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.1.0/gems/bundler-audit-0.5.0/lib/bundler/audit/scanner.rb:2:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.1.0/gems/bundler-audit-0.5.0/lib/bundler/audit/cli.rb:18:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.1.0/gems/bundler-audit-0.5.0/bin/bundle-audit:8:in `<top (required)>'
	from /usr/local/bin/bundle-audit:23:in `load'
	from /usr/local/bin/bundle-audit:23:in `<main>'
```

**Comment by postmodern** [comment]
`$HOME` isn't set. Try running it within bash or explicitly loading in `/etc/environment`.
