### ISSUE TITLE
uninitialized constant Thor::Shell::Color (NameError)

### ISSUE THREAD

**Issue by darrennix** [rubysec/bundler-audit#160]
Steps to reproduce:

```
gem install bundler-audit
bundle exec bundle-audit update
=>
/Users/darren/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/shell.rb:17:in `shell': uninitialized constant Thor::Shell::Color (NameError)
    from /Users/darren/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:439:in `start'
    from /Users/darren/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-audit-0.5.0/bin/bundle-audit:10:in `<top (required)>'
    from /Users/darren/.rbenv/versions/2.2.1/bin/bundle-audit:23:in `load'
    from /Users/darren/.rbenv/versions/2.2.1/bin/bundle-audit:23:in `<main>'
```

gemfile.lock

```
GIT
  remote: git://github.com/carrierwaveuploader/carrierwave.git
  revision: 98d73a9350478a34ea227595f172c283630356bf
  specs:
    carrierwave (0.11.0)
      activemodel (>= 4.0.0)
      activesupport (>= 4.0.0)
      mime-types (>= 1.16)

GIT
  remote: https://github.com/rest-client/rest-client.git
  revision: 677f3164c71a52f0ead7000bf7f4cbba59736a19
  tag: v2.0.0.rc2
  specs:
    rest-client (2.0.0.rc2)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 3.0)
      netrc (~> 0.8)

GEM
  remote: https://rubygems.org/
  specs:
    Ziggeo (1.06)
      httmultiparty
      httparty (~> 0.13.5)
    actionmailer (4.2.3)
      actionpack (= 4.2.3)
      actionview (= 4.2.3)
      activejob (= 4.2.3)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.3)
      actionview (= 4.2.3)
      activesupport (= 4.2.3)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionpack-action_caching (1.1.1)
      actionpack (>= 4.0.0, < 5.0)
    actionview (4.2.3)
      activesupport (= 4.2.3)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    active_median (0.1.3)
      activerecord
    activejob (4.2.3)
      activesupport (= 4.2.3)
      globalid (>= 0.3.0)
    activemodel (4.2.3)
      activesupport (= 4.2.3)
      builder (~> 3.1)
    activerecord (4.2.3)
      activemodel (= 4.2.3)
      activesupport (= 4.2.3)
      arel (~> 6.0)
    activesupport (4.2.3)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.4.0)
    after_the_deadline (0.1.3)
      crack
    arel (6.0.3)
    ast (2.2.0)
    autoparse (0.3.3)
      addressable (>= 2.3.1)
      extlib (>= 0.9.15)
      multi_json (>= 1.0.0)
    aws-sdk (1.66.0)
      aws-sdk-v1 (= 1.66.0)
    aws-sdk-v1 (1.66.0)
      json (~> 1.4)
      nokogiri (>= 1.4.4)
    aws_cf_signer (0.1.3)
    bcrypt (3.1.10)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    browser (2.0.3)
    builder (3.2.2)
    bullet (5.0.0)
      activesupport (>= 3.0.0)
      uniform_notifier (~> 1.9.0)
    bundler-audit (0.5.0)
      bundler (~> 1.2)
      thor (~> 0.18)
    byebug (8.2.2)
    callsite (0.0.11)
    capybara (2.7.1)
      addressable
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    capybara-screenshot (1.0.13)
      capybara (>= 1.0, < 3)
      launchy
    chartkick (1.4.1)
    cliver (0.3.2)
    cloudinary (1.1.6)
      aws_cf_signer
      rest-client
    colorize (0.7.7)
    commonjs (0.2.7)
    concurrent-ruby (1.0.0)
    countries (1.2.5)
      currencies (~> 0.4.2)
      i18n_data (~> 0.7.0)
    crack (0.4.3)
      safe_yaml (~> 1.0.0)
    currencies (0.4.2)
    dalli (2.7.5)
    database_cleaner (1.5.3)
    debug_inspector (0.0.2)
    delayed_job (4.1.1)
      activesupport (>= 3.0, < 5.0)
    delayed_job_active_record (4.1.0)
      activerecord (>= 3.0, < 5)
      delayed_job (>= 3.0, < 5)
    delayed_job_web (1.2.10)
      activerecord (> 3.0.0)
      delayed_job (> 2.0.3)
      sinatra (>= 1.4.4)
    devise (3.5.6)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    devise-async (0.10.2)
      devise (>= 3.2, < 4.0)
    diff-lcs (1.2.5)
    domain_name (0.5.20160310)
      unf (>= 0.0.5, < 1.0.0)
    ejs (1.1.1)
    email_spec (2.0.0)
      htmlentities (~> 4.3.3)
      launchy (~> 2.1)
      mail (~> 2.6.3)
    erubis (2.7.0)
    execjs (2.6.0)
    extlib (0.9.16)
    factory_girl (4.5.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.6.0)
      factory_girl (~> 4.5.0)
      railties (>= 3.0.0)
    faker (1.6.1)
      i18n (~> 0.5)
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    firebase (0.2.6)
      httpclient
      json
    friendly_id (5.1.0)
      activerecord (>= 4.0.0)
    fuubar (2.0.0)
      rspec (~> 3.0)
      ruby-progressbar (~> 1.4)
    git-version-bump (0.15.1)
    globalid (0.3.6)
      activesupport (>= 4.1.0)
    google-api-client (0.8.6)
      activesupport (>= 3.2)
      addressable (~> 2.3)
      autoparse (~> 0.3)
      extlib (~> 0.9)
      faraday (~> 0.9)
      googleauth (~> 0.3)
      launchy (~> 2.4)
      multi_json (~> 1.10)
      retriable (~> 1.4)
      signet (~> 0.6)
    google_drive (1.0.5)
      google-api-client (>= 0.7.0, < 0.9)
      nokogiri (>= 1.4.4, != 1.5.2, != 1.5.1)
      oauth (>= 0.3.6)
      oauth2 (>= 0.5.0)
    googleauth (0.5.1)
      faraday (~> 0.9)
      jwt (~> 1.4)
      logging (~> 2.0)
      memoist (~> 0.12)
      multi_json (~> 1.11)
      os (~> 0.9)
      signet (~> 0.7)
    gretel (3.0.8)
      rails (>= 3.2.0)
    groupdate (2.5.1)
      activesupport (>= 3)
    hashdiff (0.2.3)
    hashie (3.4.3)
    htmlentities (4.3.4)
    httmultiparty (0.3.16)
      httparty (>= 0.7.3)
      mimemagic
      multipart-post
    http-cookie (1.0.2)
      domain_name (~> 0.5)
    httparty (0.13.7)
      json (~> 1.8)
      multi_xml (>= 0.5.2)
    httpclient (2.7.1)
    i18n (0.7.0)
    i18n_data (0.7.0)
    inflection (1.0.0)
    jbuilder (2.4.1)
      activesupport (>= 3.0.0, < 5.1)
      multi_json (~> 1.2)
    jquery-rails (4.1.0)
      rails-dom-testing (~> 1.0)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    json (1.8.3)
    json-schema (2.5.0)
      addressable (~> 2.3)
    jwt (1.5.1)
    kaminari (0.16.3)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    launchy (2.4.3)
      addressable (~> 2.3)
    less (2.6.0)
      commonjs (~> 0.2.7)
    less-rails (2.7.1)
      actionpack (>= 4.0)
      less (~> 2.6.0)
      sprockets (> 2, < 4)
      tilt
    libv8 (3.16.14.13)
    little-plugger (1.1.4)
    logging (2.0.0)
      little-plugger (~> 1.1)
      multi_json (~> 1.10)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    memoist (0.14.0)
    meta_request (0.3.4)
      callsite (~> 0.0, >= 0.0.11)
      rack-contrib (~> 1.1)
      railties (>= 3.0.0, < 5.0.0)
    mime-types (2.99.2)
    mimemagic (0.3.1)
    mini_portile2 (2.1.0)
    minitest (5.9.0)
    multi_json (1.12.0)
    multi_xml (0.5.5)
    multipart-post (2.0.0)
    netrc (0.11.0)
    newrelic_rpm (3.14.2.312)
    nilify_blanks (1.2.1)
      activerecord (>= 3.0.0)
      activesupport (>= 3.0.0)
    nokogiri (1.6.8)
      mini_portile2 (~> 2.1.0)
      pkg-config (~> 1.1.7)
    oauth (0.4.7)
    oauth2 (1.1.0)
      faraday (>= 0.8, < 0.10)
      jwt (~> 1.0, < 1.5.2)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 3)
    opentok (2.3.3)
      activesupport (>= 2.0)
      addressable (~> 2.3)
      httparty (~> 0.13.1)
    orm_adapter (0.5.0)
    os (0.9.6)
    paranoia (2.1.5)
      activerecord (~> 4.0)
    parser (2.3.0.4)
      ast (~> 2.2)
    pg (0.18.4)
    phantomjs (2.1.1.0)
    phony (2.15.15)
    phony_rails (0.12.11)
      activesupport (>= 3.0)
      phony (~> 2.12)
    pkg-config (1.1.7)
    poltergeist (1.10.0)
      capybara (~> 2.1)
      cliver (~> 0.3.1)
      websocket-driver (>= 0.2.0)
    polyamorous (1.3.0)
      activerecord (>= 3.0)
    powerpack (0.1.1)
    public_suffix (1.5.3)
    puma (2.16.0)
    quiet_assets (1.1.0)
      railties (>= 3.1, < 5.0)
    rack (1.6.4)
    rack-contrib (1.4.0)
      git-version-bump (~> 0.15)
      rack (~> 1.4)
    rack-protection (1.5.3)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    railroady (1.4.2)
    rails (4.2.3)
      actionmailer (= 4.2.3)
      actionpack (= 4.2.3)
      actionview (= 4.2.3)
      activejob (= 4.2.3)
      activemodel (= 4.2.3)
      activerecord (= 4.2.3)
      activesupport (= 4.2.3)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.3)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.7)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    rails_12factor (0.0.3)
      rails_serve_static_assets
      rails_stdout_logging
    rails_autolink (1.1.6)
      rails (> 3.1)
    rails_serve_static_assets (0.0.5)
    rails_stdout_logging (0.0.4)
    railties (4.2.3)
      actionpack (= 4.2.3)
      activesupport (= 4.2.3)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rainbow (2.1.0)
    rake (11.2.2)
    ransack (1.7.0)
      actionpack (>= 3.0)
      activerecord (>= 3.0)
      activesupport (>= 3.0)
      i18n
      polyamorous (~> 1.2)
    redcarpet (3.3.4)
    ref (2.0.0)
    responders (2.1.1)
      railties (>= 4.2.0, < 5.1)
    retriable (1.4.1)
    rickshaw (0.3.1)
    rollbar (2.11.3)
      multi_json
    rspec (3.4.0)
      rspec-core (~> 3.4.0)
      rspec-expectations (~> 3.4.0)
      rspec-mocks (~> 3.4.0)
    rspec-core (3.4.2)
      rspec-support (~> 3.4.0)
    rspec-expectations (3.4.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.4.0)
    rspec-mocks (3.4.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.4.0)
    rspec-rails (3.4.2)
      actionpack (>= 3.0, < 4.3)
      activesupport (>= 3.0, < 4.3)
      railties (>= 3.0, < 4.3)
      rspec-core (~> 3.4.0)
      rspec-expectations (~> 3.4.0)
      rspec-mocks (~> 3.4.0)
      rspec-support (~> 3.4.0)
    rspec-support (3.4.1)
    rubocop (0.37.1)
      parser (>= 2.3.0.4, < 3.0)
      powerpack (~> 0.1)
      rainbow (>= 1.99.1, < 3.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (~> 0.3)
    ruby-progressbar (1.7.5)
    safe_yaml (1.0.4)
    sanitize_email (1.1.7)
    scrub_rb (1.0.1)
    shoulda-callback-matchers (1.1.4)
      activesupport (>= 3)
    shoulda-matchers (3.1.1)
      activesupport (>= 4.0.0)
    signet (0.7.2)
      addressable (~> 2.3)
      faraday (~> 0.9)
      jwt (~> 1.5)
      multi_json (~> 1.10)
    sinatra (1.4.7)
      rack (~> 1.5)
      rack-protection (~> 1.4)
      tilt (>= 1.3, < 3)
    spring (1.6.3)
    sprockets (3.5.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.0.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    textacular (3.2.2)
      activerecord (>= 3.0, < 5.0)
    therubyracer (0.12.2)
      libv8 (~> 3.16.14.0)
      ref
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (2.0.2)
    twilio-ruby (4.11.0)
      builder (>= 2.1.2)
      jwt (~> 1.0)
      multi_json (>= 1.3.0)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.2)
    unicode-display_width (0.3.1)
    uniform_notifier (1.9.0)
    validates_email_format_of (1.6.3)
      i18n
    vcr (3.0.1)
    warden (1.2.6)
      rack (>= 1.0)
    web-console (2.2.1)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)
    webmock (1.22.6)
      addressable (>= 2.3.6)
      crack (>= 0.3.2)
      hashdiff
    websocket-driver (0.6.4)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.2)
    xpath (2.0.0)
      nokogiri (~> 1.3)
    yui-compressor (0.12.0)
    zendesk_api (1.13.4)
      faraday (~> 0.9)
      hashie (>= 1.2, < 4.0, != 3.3.0)
      inflection
      mime-types (~> 2.99)
      multipart-post (~> 2.0)
      scrub_rb (~> 1.0.1)

PLATFORMS
  ruby

DEPENDENCIES
  Ziggeo
  actionpack-action_caching
  active_median
  after_the_deadline
  aws-sdk (~> 1.9)
  browser
  bullet
  bundler-audit
  byebug
  capybara (~> 2.7.1)
  capybara-screenshot
  carrierwave!
  chartkick
  cloudinary
  colorize
  countries
  dalli
  database_cleaner (~> 1.5.1)
  delayed_job_active_record
  delayed_job_web
  devise
  devise-async
  ejs
  email_spec
  factory_girl_rails
  faker
  firebase
  friendly_id
  fuubar
  google-api-client (= 0.8.6)
  google_drive
  googleauth
  gretel
  groupdate
  hashie
  jbuilder (~> 2.0)
  jquery-rails (>= 4.0.4)
  json-schema (~> 2.5.0)
  kaminari
  less-rails (>= 2.7)
  meta_request
  mimemagic
  newrelic_rpm
  nilify_blanks
  oauth
  opentok (~> 2.3)
  paranoia (~> 2.0)
  pg
  phantomjs
  phony_rails
  poltergeist
  public_suffix
  puma
  quiet_assets
  railroady
  rails (= 4.2.3)
  rails_12factor
  rails_autolink
  ransack (~> 1.7)
  redcarpet
  rest-client!
  rickshaw
  rollbar
  rspec-rails
  rubocop
  sanitize_email
  shoulda-callback-matchers (~> 1.1.2)
  shoulda-matchers
  spring
  sprockets
  textacular (~> 3.0)
  therubyracer
  twilio-ruby
  tzinfo
  uglifier (>= 1.3.0)
  validates_email_format_of
  vcr
  web-console (~> 2.2.1)
  webmock
  yui-compressor (~> 0.12.0)
  zendesk_api
```

Have tried 
1. just running `bundle-audit`
2. `bundle update thor`

**Comment by postmodern** [comment]
Try running `bundler update bundler-audit`. Since you're `bundle exec`ing, it's still using bundler-audit 0.5.0, instead of more recent 0.6.0 available on rubygems.org.

**Comment by postmodern** [comment]
Closing this as it's an old bundler-audit/thor bug.
