### ISSUE TITLE
Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered (ArgumentError)

### ISSUE THREAD

**Issue by HarlemSquirrel** [rubysec/bundler-audit#260]
```
/home/$USER/.rvm/gems/ruby-2.7.1/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: already initialized constant Bundler::FileUtils::VERSION
/home/$USER/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: previous definition of VERSION was here
/home/$USER/.rvm/gems/ruby-2.7.1/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: already initialized constant Bundler::FileUtils::Entry_::S_IF_DOOR
/home/$USER/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: previous definition of S_IF_DOOR was here
/home/$USER/.rvm/gems/ruby-2.7.1/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: already initialized constant Bundler::FileUtils::Entry_::DIRECTORY_TERM
/home/$USER/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: previous definition of DIRECTORY_TERM was here
/home/$USER/.rvm/gems/ruby-2.7.1/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: already initialized constant Bundler::FileUtils::OPT_TABLE
/home/$USER/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: previous definition of OPT_TABLE was here
/home/$USER/.rvm/gems/ruby-2.7.1/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: already initialized constant Bundler::FileUtils::LOW_METHODS
/home/$USER/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: previous definition of LOW_METHODS was here
/home/$USER/.rvm/gems/ruby-2.7.1/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: already initialized constant Bundler::FileUtils::METHODS
/home/$USER/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: previous definition of METHODS was here
Traceback (most recent call last):
  18: from /home/$USER/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:24:in `<main>'
  17: from /home/$USER/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:24:in `eval'
  16: from /home/$USER/.rvm/gems/ruby-2.7.1/bin/bundle-audit:23:in `<main>'
  15: from /home/$USER/.rvm/gems/ruby-2.7.1/bin/bundle-audit:23:in `load'
  14: from /home/$USER/.rvm/gems/ruby-2.7.1/gems/bundler-audit-0.6.1/bin/bundle-audit:8:in `<top (required)>'
  13: from /home/$USER/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
  12: from /home/$USER/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
  11: from /home/$USER/.rvm/gems/ruby-2.7.1/gems/bundler-audit-0.6.1/lib/bundler/audit/cli.rb:18:in `<top (required)>'
  10: from /home/$USER/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
   9: from /home/$USER/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
   8: from /home/$USER/.rvm/gems/ruby-2.7.1/gems/bundler-audit-0.6.1/lib/bundler/audit/scanner.rb:1:in `<top (required)>'
   7: from /home/$USER/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
   6: from /home/$USER/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
   5: from /home/$USER/.rvm/gems/ruby-2.7.1/gems/bundler-2.1.4/lib/bundler.rb:7:in `<top (required)>'
   4: from /home/$USER/.rvm/gems/ruby-2.7.1/gems/bundler-2.1.4/lib/bundler.rb:7:in `require_relative'
   3: from /home/$USER/.rvm/gems/ruby-2.7.1/gems/bundler-2.1.4/lib/bundler/errors.rb:3:in `<top (required)>'
   2: from /home/$USER/.rvm/gems/ruby-2.7.1/gems/bundler-2.1.4/lib/bundler/errors.rb:20:in `<module:Bundler>'
   1: from /home/$USER/.rvm/gems/ruby-2.7.1/gems/bundler-2.1.4/lib/bundler/errors.rb:20:in `<class:GemfileError>'
/home/$USER/.rvm/gems/ruby-2.7.1/gems/bundler-2.1.4/lib/bundler/errors.rb:9:in `status_code': Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered (ArgumentError)
```

**Comment by mcandre** [comment]
Same.

Ruby 2.7.1 via RVM, on Homebrew, on macOS 10.15.4 Catalina.

**Comment by asaaki** [comment]
This is not an issue with bundle-audit, but the Ruby enviroment itself:
https://github.com/rubygems/rubygems/issues/3551

Quickfix is to run `gem update --system` first:

```shell
# example
gem update --system
gem update --force bundler
gem install bundler-audit
bundle-audit check --update
```

**Comment by billyabm** [comment]
You have to set `BUNDLE_PATH`,  check the bundle [documentation](https://bundler.io/v0.9/bundle_install.html)

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by postmodern** [comment]
Closing as this was an old upstream issue.
