### ISSUE TITLE
bundler-audit-0.7.0/data/ruby-advisory-db is not a directory (ArgumentError)

### ISSUE THREAD

**Issue by mtsmfm** [rubysec/bundler-audit#265]
Is this intentional?

## Steps to reproduce

```
$ docker run --rm -it -e LANG=C.UTF-8 ruby:2.7.1-buster bash
# bundle init
# bundle
# gem install bundler-audit -v 0.6.1
# bundle audit
No vulnerabilities found
# gem uninstall bundler-audit
# gem install bundler-audit -v 0.7.0
# bundle audit
"/usr/local/bundle/gems/bundler-audit-0.7.0/data/ruby-advisory-db" is not a directory (ArgumentError)
```

## Result

```
$ docker run --rm -it -e LANG=C.UTF-8 ruby:2.7.1-buster bash
root@b7456b6a05e4:/# bundle init
Writing new Gemfile to //Gemfile
root@b7456b6a05e4:/# bundle
The Gemfile specifies no dependencies
Resolving dependencies...
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
root@b7456b6a05e4:/# gem install bundler-audit -v 0.6.1
Fetching bundler-audit-0.6.1.gem
Fetching thor-0.20.3.gem
Successfully installed thor-0.20.3
Successfully installed bundler-audit-0.6.1
2 gems installed
root@b7456b6a05e4:/# bundle audit
No vulnerabilities found
root@b7456b6a05e4:/# gem uninstall bundler-audit
Remove executables:
        bundle-audit, bundler-audit

in addition to the gem? [Yn]  y
Removing bundle-audit
Removing bundler-audit
Successfully uninstalled bundler-audit-0.6.1
root@b7456b6a05e4:/# gem install bundler-audit -v 0.7.0
Fetching bundler-audit-0.7.0.gem
Successfully installed bundler-audit-0.7.0
1 gem installed
root@b7456b6a05e4:/# bundle audit
Traceback (most recent call last):
        13: from /usr/local/bundle/bin/bundler-audit:23:in `<main>'
        12: from /usr/local/bundle/bin/bundler-audit:23:in `load'
        11: from /usr/local/bundle/gems/bundler-audit-0.7.0/bin/bundler-audit:3:in `<top (required)>'
        10: from /usr/local/bundle/gems/bundler-audit-0.7.0/bin/bundler-audit:3:in `load'
         9: from /usr/local/bundle/gems/bundler-audit-0.7.0/bin/bundle-audit:10:in `<top (required)>'
         8: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
         7: from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
         6: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         5: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         4: from /usr/local/bundle/gems/bundler-audit-0.7.0/lib/bundler/audit/cli.rb:41:in `check'
         3: from /usr/local/bundle/gems/bundler-audit-0.7.0/lib/bundler/audit/cli.rb:41:in `new'
         2: from /usr/local/bundle/gems/bundler-audit-0.7.0/lib/bundler/audit/scanner.rb:44:in `initialize'
         1: from /usr/local/bundle/gems/bundler-audit-0.7.0/lib/bundler/audit/scanner.rb:44:in `new'
/usr/local/bundle/gems/bundler-audit-0.7.0/lib/bundler/audit/database.rb:57:in `initialize': "/usr/local/bundle/gems/bundler-audit-0.7.0/data/ruby-advisory-db" is not a directory (ArgumentError)
```

**Comment by postmodern** [comment]
Ah damn it. I forgot to re-run `git submodule init` and `git submodule update` to re-populate `data/ruby-advisory-db` so the built-in ruby-advisory-db never got packaged. Embarrassingly stupid mistake. Preferences on a 0.7.0 or 0.7.0.1 release?

**Comment by vaporyhumo** [comment]
You meant 0.7.1? That's what I'd go for. Probably should yank `0.7.0`.

**Comment by postmodern** [comment]
Hotfix 0.7.0.1 pushed out and tested locally. A fourth version number usually denotes hotfixes for dumb show-stopping bugs. Any additional minor bug fixes will go into a 0.7.1 release.

**Comment by vaporyhumo** [comment]
Thanks for aclaration, take a look at the typo I pointed out in the rake task.

**Comment by mtsmfm** [comment]
I've confirmed it's fixed now!

```
$ docker run --rm -it -e LANG=C.UTF-8 ruby:2.7.1-buster bash
root@941b8c4125b8:/# bundle init
Writing new Gemfile to //Gemfile
root@941b8c4125b8:/# bundle
The Gemfile specifies no dependencies
Resolving dependencies...
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
root@941b8c4125b8:/# gem install bundler-audit
Fetching bundler-audit-0.7.0.1.gem
Fetching thor-1.0.1.gem
Successfully installed thor-1.0.1
Successfully installed bundler-audit-0.7.0.1
2 gems installed
root@941b8c4125b8:/# bundle audit
No vulnerabilities found
```
