### ISSUE TITLE
Error running bundler-audit

### ISSUE THREAD

**Issue by natebird** [rubysec/bundler-audit#290]
**Versions**
Ruby: 2.7.2
gem version: 0.7.0.1

I receive the following error when running bundler-audit:

```ruby
ｘ project ~ bundle exec bundle audit check                                
Traceback (most recent call last):
	36: from /Users/me/.gem/ruby/2.7.2/bin/bundler-audit:23:in `<main>'
	35: from /Users/me/.gem/ruby/2.7.2/bin/bundler-audit:23:in `load'
	34: from /Users/me/.gem/ruby/2.7.2/gems/bundler-audit-0.7.0.1/bin/bundler-audit:3:in `<top (required)>'
	33: from /Users/me/.gem/ruby/2.7.2/gems/bundler-audit-0.7.0.1/bin/bundler-audit:3:in `load'
	32: from /Users/me/.gem/ruby/2.7.2/gems/bundler-audit-0.7.0.1/bin/bundle-audit:10:in `<top (required)>'
	31: from /Users/me/.gem/ruby/2.7.2/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	30: from /Users/me/.gem/ruby/2.7.2/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	29: from /Users/me/.gem/ruby/2.7.2/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	28: from /Users/me/.gem/ruby/2.7.2/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	27: from /Users/me/.gem/ruby/2.7.2/gems/bundler-audit-0.7.0.1/lib/bundler/audit/cli.rb:44:in `check'
	26: from /Users/me/.gem/ruby/2.7.2/gems/bundler-audit-0.7.0.1/lib/bundler/audit/scanner.rb:74:in `scan'
	25: from /Users/me/.gem/ruby/2.7.2/gems/bundler-audit-0.7.0.1/lib/bundler/audit/scanner.rb:102:in `scan_sources'
	24: from /Users/me/.gem/ruby/2.7.2/gems/bundler-audit-0.7.0.1/lib/bundler/audit/scanner.rb:102:in `map'
	23: from /Users/me/.gem/ruby/2.7.2/gems/bundler-audit-0.7.0.1/lib/bundler/audit/scanner.rb:112:in `block in scan_sources'
	22: from /Users/me/.gem/ruby/2.7.2/gems/bundler-audit-0.7.0.1/lib/bundler/audit/scanner.rb:112:in `each'
	21: from /Users/me/.gem/ruby/2.7.2/gems/bundler-audit-0.7.0.1/lib/bundler/audit/scanner.rb:113:in `block (2 levels) in scan_sources'
	20: from /Users/me/.gem/ruby/2.7.2/gems/bundler-audit-0.7.0.1/lib/bundler/audit/scanner.rb:172:in `internal_source?'
	19: from /Users/me/.gem/ruby/2.7.2/gems/bundler-audit-0.7.0.1/lib/bundler/audit/scanner.rb:184:in `internal_host?'
	18: from /Users/me/.rubies/ruby-2.7.2/lib/ruby/2.7.0/resolv.rb:51:in `getaddresses'
	17: from /Users/me/.rubies/ruby-2.7.2/lib/ruby/2.7.0/resolv.rb:102:in `getaddresses'
	16: from /Users/me/.rubies/ruby-2.7.2/lib/ruby/2.7.0/resolv.rb:115:in `each_address'
	15: from /Users/me/.rubies/ruby-2.7.2/lib/ruby/2.7.0/resolv.rb:115:in `each'
	14: from /Users/me/.rubies/ruby-2.7.2/lib/ruby/2.7.0/resolv.rb:116:in `block in each_address'
	13: from /Users/me/.rubies/ruby-2.7.2/lib/ruby/2.7.0/resolv.rb:402:in `each_address'
	12: from /Users/me/.rubies/ruby-2.7.2/lib/ruby/2.7.0/resolv.rb:507:in `each_resource'
	11: from /Users/me/.rubies/ruby-2.7.2/lib/ruby/2.7.0/resolv.rb:521:in `fetch_resource'
	10: from /Users/me/.rubies/ruby-2.7.2/lib/ruby/2.7.0/resolv.rb:1119:in `resolv'
	 9: from /Users/me/.rubies/ruby-2.7.2/lib/ruby/2.7.0/resolv.rb:1119:in `each'
	 8: from /Users/me/.rubies/ruby-2.7.2/lib/ruby/2.7.0/resolv.rb:1121:in `block in resolv'
	 7: from /Users/me/.rubies/ruby-2.7.2/lib/ruby/2.7.0/resolv.rb:1121:in `each'
	 6: from /Users/me/.rubies/ruby-2.7.2/lib/ruby/2.7.0/resolv.rb:1122:in `block (2 levels) in resolv'
	 5: from /Users/me/.rubies/ruby-2.7.2/lib/ruby/2.7.0/resolv.rb:1122:in `each'
	 4: from /Users/me/.rubies/ruby-2.7.2/lib/ruby/2.7.0/resolv.rb:1124:in `block (3 levels) in resolv'
	 3: from /Users/me/.rubies/ruby-2.7.2/lib/ruby/2.7.0/resolv.rb:531:in `block in fetch_resource'
	 2: from /Users/me/.rubies/ruby-2.7.2/lib/ruby/2.7.0/resolv.rb:665:in `request'
	 1: from /Users/me/.rubies/ruby-2.7.2/lib/ruby/2.7.0/resolv.rb:803:in `send'
/Users/me/.rubies/ruby-2.7.2/lib/ruby/2.7.0/resolv.rb:803:in `send': No buffer space available - sendto(2) for "2001:558:feed::1" port 53 (Errno::ENOBUFS)
```

Any ideas about what would cause this? I've read about Ruby opening more than 1024 sockets can cause this. Our CI server doesn't have any issues running `bundler-audit` but I can't run it on my development machine.

**Comment by postmodern** [comment]
Googling `Errno::ENOBUFS` says that it's related to when your system or VM is running out of memory.

**Comment by natebird** [comment]
Yeah, I've Googled it and found the same. What is odd is this is a 32 GB MacBook Pro. I don't think I'm out of memory. I get the same after reboots and on another machine with 16GB RAM. It seems to be specific to my configuration. I'll keep researching.

Oh, and sorry for the slow response. I was off the grid for a while.
