### ISSUE TITLE
it crashes on Gemfile.lock with ftpd (0.2.1)

### ISSUE THREAD

**Issue by yltsrc** [rubysec/bundler-audit#65]
bundler-audit version = 0.3.0

I can't reproduce it on my mac, but it continuously crashing on travis-ci.org

```
bundle-audit update; bundle-audit check
```

Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.0.0)
      actionpack (= 4.0.0)
      mail (~> 2.5.3)
    actionpack (4.0.0)
      activesupport (= 4.0.0)
      builder (~> 3.1.0)
      erubis (~> 2.7.0)
      rack (~> 1.5.2)
      rack-test (~> 0.6.2)
    activemodel (4.0.0)
      activesupport (= 4.0.0)
      builder (~> 3.1.0)
    activerecord (4.0.0)
      activemodel (= 4.0.0)
      activerecord-deprecated_finders (~> 1.0.2)
      activesupport (= 4.0.0)
      arel (~> 4.0.0)
    activerecord-deprecated_finders (1.0.3)
    activesupport (4.0.0)
      i18n (~> 0.6, >= 0.6.4)
      minitest (~> 4.2)
      multi_json (~> 1.3)
      thread_safe (~> 0.1)
      tzinfo (~> 0.3.37)
    arel (4.0.2)
    atomic (1.1.14)
    builder (3.1.4)
    erubis (2.7.0)
    ftpd (0.2.1)
      memoizer (~> 1.0.1)
    hike (1.2.3)
    i18n (0.6.9)
    mail (2.5.4)
      mime-types (~> 1.16)
      treetop (~> 1.4.8)
    memoizer (1.0.1)
    mime-types (1.25.1)
    minitest (4.7.5)
    multi_json (1.8.4)
    polyglot (0.3.3)
    rack (1.5.2)
    rack-test (0.6.2)
      rack (>= 1.0)
    rails (4.0.0)
      actionmailer (= 4.0.0)
      actionpack (= 4.0.0)
      activerecord (= 4.0.0)
      activesupport (= 4.0.0)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.0.0)
      sprockets-rails (~> 2.0.0)
    railties (4.0.0)
      actionpack (= 4.0.0)
      activesupport (= 4.0.0)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.1.1)
    sprockets (2.10.1)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.0.1)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (~> 2.8)
    thor (0.18.1)
    thread_safe (0.1.3)
      atomic
    tilt (1.4.1)
    treetop (1.4.15)
      polyglot
      polyglot (>= 0.3.1)
    tzinfo (0.3.38)

PLATFORMS
  ruby

DEPENDENCIES
  ftpd (= 0.2.1)
  rails (= 4.0.0)
```

Exception backtrace:

```
/home/travis/.rvm/gems/ruby-2.1.0/gems/bundler-1.5.2/lib/bundler/vendor/thor/shell/basic.rb:80:in `say': undefined method `end_with?' for #<Gem::Version "0.2.1"> (NoMethodError)
    from /home/travis/.rvm/gems/ruby-2.1.0/gems/bundler-1.5.2/lib/bundler/vendor/thor/shell.rb:59:in `say'
    from /home/travis/.rvm/gems/ruby-2.1.0/gems/bundler-audit-0.3.0/lib/bundler/audit/cli.rb:77:in `say'
    from /home/travis/.rvm/gems/ruby-2.1.0/gems/bundler-audit-0.3.0/lib/bundler/audit/cli.rb:89:in `print_advisory'
    from /home/travis/.rvm/gems/ruby-2.1.0/gems/bundler-audit-0.3.0/lib/bundler/audit/cli.rb:46:in `block in check'
    from /home/travis/.rvm/gems/ruby-2.1.0/gems/bundler-audit-0.3.0/lib/bundler/audit/scanner.rb:87:in `block (2 levels) in scan'
    from /home/travis/.rvm/gems/ruby-2.1.0/gems/bundler-audit-0.3.0/lib/bundler/audit/database.rb:164:in `block in check_gem'
    from /home/travis/.rvm/gems/ruby-2.1.0/gems/bundler-audit-0.3.0/lib/bundler/audit/database.rb:139:in `block in advisories_for'
    from /home/travis/.rvm/gems/ruby-2.1.0/gems/bundler-audit-0.3.0/lib/bundler/audit/database.rb:227:in `glob'
    from /home/travis/.rvm/gems/ruby-2.1.0/gems/bundler-audit-0.3.0/lib/bundler/audit/database.rb:227:in `each_advisory_path_for'
    from /home/travis/.rvm/gems/ruby-2.1.0/gems/bundler-audit-0.3.0/lib/bundler/audit/database.rb:138:in `advisories_for'
    from /home/travis/.rvm/gems/ruby-2.1.0/gems/bundler-audit-0.3.0/lib/bundler/audit/database.rb:162:in `check_gem'
    from /home/travis/.rvm/gems/ruby-2.1.0/gems/bundler-audit-0.3.0/lib/bundler/audit/scanner.rb:85:in `block in scan'
    from /home/travis/.rvm/gems/ruby-2.1.0/gems/bundler-audit-0.3.0/lib/bundler/audit/scanner.rb:84:in `each'
    from /home/travis/.rvm/gems/ruby-2.1.0/gems/bundler-audit-0.3.0/lib/bundler/audit/scanner.rb:84:in `scan'
    from /home/travis/.rvm/gems/ruby-2.1.0/gems/bundler-audit-0.3.0/lib/bundler/audit/cli.rb:39:in `check'
    from /home/travis/.rvm/gems/ruby-2.1.0/gems/bundler-1.5.2/lib/bundler/vendor/thor/command.rb:27:in `run'
    from /home/travis/.rvm/gems/ruby-2.1.0/gems/bundler-1.5.2/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
    from /home/travis/.rvm/gems/ruby-2.1.0/gems/bundler-1.5.2/lib/bundler/vendor/thor.rb:363:in `dispatch'
    from /home/travis/.rvm/gems/ruby-2.1.0/gems/bundler-1.5.2/lib/bundler/vendor/thor/base.rb:440:in `start'
    from /home/travis/.rvm/gems/ruby-2.1.0/gems/bundler-audit-0.3.0/bin/bundle-audit:10:in `<top (required)>'
    from /home/travis/.rvm/gems/ruby-2.1.0/bin/bundle-audit:23:in `load'
    from /home/travis/.rvm/gems/ruby-2.1.0/bin/bundle-audit:23:in `<main>'
```

**Comment by bigxiang** [comment]
:+1: to release.
